import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight:['400', '600','700'],
  subsets:['latin']
})


export const metadata = {
  title: {
    default:'Anamol Hasan',
    template:'%s | Anamol Hasan'
  },
    keywords: ['Next.js', 'React', 'JavaScript', "Learning", "PlayGround"],
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} ${geistMono.variable} antialiased`}
      >
       <Navbar />
        {children}
      </body>
    </html>
  );
}
